#!/bin/bash

if [ $# -eq 0 ]
    then
        echo Usage: deploy [go][dry];
elif [ $1 == "go" ]
    then
        echo "Running deploy..."
        rsync -az --force --delete --progress --chmod 777 --exclude-from=exclude_list.txt -e "ssh -p22" ./ docent@146.59.94.177:/home/docent/dash_fastapi_docker
        echo "Docker build and run container"
        sshpass -p "adasiek" ssh root@146.59.94.177 "cd /home/docent/dash_fastapi_docker; ./build; ./run"
elif [ $1 == "dry" ]
    then
        echo "Running dry-run";
        rsync --dry-run -az --force --delete --progress --chmod 777 --exclude-from=exclude_list.txt "ssh -p22" ./ docent@146.59.94.177:/home/docent/dash_fastapi_docker
else
    echo Usage: deploy [go][dry];
fi
